# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtigoCientifico',
            new_name='ArtigoCientifico',
        ),
        migrations.RenameField(
            model_name='pessoajuridica',
            old_name='cnjp',
            new_name='cnpj',
        ),
    ]
