# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20170327_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='artigos',
            field=models.CharField(max_length=200, verbose_name='idsArtigos'),
        ),
    ]
